alias 'web=/data/data/com.termux/files/home/.toolbox --web &'
alias 'gw=/data/data/com.termux/files/home/.toolbox --gw'
alias 'laj=/data/data/com.termux/files/home/jiankangji --laj'
alias 'lac=/data/data/com.termux/files/home/jiankangji --lac'
alias 'laq=/data/data/com.termux/files/home/jiankangji --laq'
alias 'lat=/data/data/com.termux/files/home/jiankangji --lat'
alias 'lab=/data/data/com.termux/files/home/jiankangji --lab'
alias 'jnj=/data/data/com.termux/files/home/jiankangji --jnj'
alias 'jnh=/data/data/com.termux/files/home/jiankangji --jnh'
alias 'jnq=/data/data/com.termux/files/home/jiankangji --jnq'
alias 'jnt=/data/data/com.termux/files/home/jiankangji --jnt'
alias 'jnb=/data/data/com.termux/files/home/jiankangji --jnb'
alias 'jkj=/data/data/com.termux/files/home/jiankangji'
alias 'ql=/data/data/com.termux/files/home/.toolbox --ql'
alias 'hf=/data/data/com.termux/files/home/.toolbox --hf'
alias 'gh=/data/data/com.termux/files/home/.toolbox --github'
alias 'my=/data/data/com.termux/files/home/.toolbox --gitee'
alias 'db=/data/data/com.termux/files/home/.toolbox --db'
./.bird --ds
alias 'grep=grep --color'
alias 'll=ls -l'
alias 'fedora=proot-distro login fedora-33'
_day_=`date +%w`
[ $[_day_%6] -ne 0 ] && sshd
