#!/bin/bash
read -p 'ip address:' ip
[ `echo "$ip>4" | bc` -eq 1 ] && ethernet=ens35 || ethernet=ens34
read -p 'hostname:' hostname
nmcli connection modify $ethernet ipv4.addresses "192.168.$ip/24" ipv4.method manual connection.autoconnect yes
nmcli connection up $ethernet
hostnamectl set-hostname $hostname
