#!/bin/bash
read -p 'jihe:' j
a=0
b=1
[ $j -lt 1 ] || [ $j -gt 328 ]
[ $? -eq 0 ] && echo "out of range,1-328 is okay" && exit
j=$[j-1]
echo -n  "1 "
for i in `seq ${j:=55}`
do
	c=`echo $a+$b | bc`
	a=$b
	b=$c
	s=$[i%7+31]
	echo -en "\033[${s}m$c \033[0m"
done
echo ''
