#!/bin/bash
ql(){
echo
ls .*.sw* 2> /dev/null
[ $? -eq 2 ] && echo -e "\t\t\e[32mNO TRASH\e[0m" && exit
echo -e "\e[32m--------------------\e[0m"
while :
read -p "sure? " s
do
	if [[ ${s:=yes} =~ yes ]];then
		rm .*.sw*
		echo -e "\t\t\e[32mTRASH CLEANED UP\e[0m"
		exit
	elif [[ $s =~ no ]];then
		exit
	else
		echo -e "\e[32myes|no\e[0m"
	fi
done
}	
hf(){
clear
echo -e '\e[0m\e[?25h'
}
push(){
bpath=$PREFIX/Termuxbak/backup/hm
cd
for i in `ls`;do
[ -f $i ] && cp $i $bpath && echo -e "$i \e[32m✓\e[0m" && let e++
done
echo -e "\e[32m---------------\ncopied $e files\e[0m"
read -p "git push them all? " y
[[ "$y" =~ "no" ]] && exit
[[ "${y:=yes}" =~ "yes" ]] && rsync -r ${bpath}/ $1 && cd $1 && git add . && read -p "any remarks? " rm && git commit -m "${rm:=}`date +%Y%b%e•%X`" && git push && echo -e "$2" || echo -e "$3"
cd
}
ghl='\n\t\t\e[1m\e[32m(×)\n\t\t/|\\\e[0m'
gtl='\n\t\t\e[1m\e[31m(\e[0mG\e[31m)\e[0m'
bghl='\n\t\t\e[1m\e[31m(×)\n\t\t/|\\\e[0m'
bgtl='\n\t\t\e[1m\e[33m(\e[32mG\e[33m)\e[0m'
ghp=$HOME/termux-prc
gtp=$HOME/termux-app
case $1 in
	--github)
		push $ghp $ghl $bghl;;
	--gitee)
		push $gtp $gtl $bgtl;;
	--db)
		push $gtp $gtl $bgtl;
		push $ghp $ghl $bghl;;
	--ql)
		ql;;
	--hf)
		hf;;
	*)
		echo -e '\e[32mgithub|gitee|ql|hf\e[0m'
esac
