#!/bin/bash
ql(){
echo
ls .*.sw* 2> /dev/null
[ $? -eq 2 ] && echo -e "\t\t\e[32mNO TRASH\e[0m" && exit
echo -e "\e[32m--------------------\e[0m"
while :
read -p "sure? " s
do
	if [[ ${s:=yes} =~ yes ]];then
		rm .*.sw*
		echo -e "\t\t\e[32mTRASH CLEANED UP\e[0m"
		exit
	elif [[ $s =~ no ]];then
		exit
	else
		echo -e "\e[32myes|no\e[0m"
	fi
done
}	
hf(){
clear
echo -e '\e[0m\e[?25h'
}
mp3(){
ffmpeg -i $1 -acodec libmp3lame $2
}
push(){
local e
bpath=$PREFIX/backup
cd
for i in `ls`;do
[ -f $i ] && rsync $i $bpath && echo -e "$i \e[32m✓\e[0m" && let e++
done
echo -e "\e[32m---------------\ncopied $e files\e[0m"
read -p "git push them all? " y
echo -e "\e[1A\e[19C\e[42m${y:=yes}\e[0m"
[[ "$y" =~ "no" ]] && exit
[[ "$y" =~ "yes" ]] && rsync -r ${bpath}/ $1 && cd $1 && git add . && read -p "any remarks? " rm  && echo -e "\e[1A\e[13C\e[42m$rm\e[0m\n" && git commit -m "${rm:=}•`date +%Y%b%e•%X`" && git push && echo -e "$2" || echo -e "$3"
cd
}
ghl='\n\t\t\e[1m\e[37m(×)\n\t\t/|\\\e[0m\n'
gtl='\n\t\t\e[1m\e[31m(\e[37mG\e[31m)\e[0m\n'
bghl='\n\t\t\e[1m\e[33m(×)\n\t\t/|\\\e[0m\n'
bgtl='\n\t\t\e[1m\e[33m(\e[32mG\e[33m)\e[0m\n'
ghp=$HOME/termux-prc
gtp=$HOME/termux-app
startService(){
nginx
#php-fpm  
#nohup mysqld &> /dev/null &
sleep 1
clear
}
line(){
	echo -en "$3\e[?25l"
	for i in `seq ${#1}`
	do
		if [[ $2 =~ [[:digit:]] ]];then
			echo -en "\e[$2m${1:$[i-1]:1}"
			else
				echo -en "\e[$[i%7+31]m$2\e[0m"
		fi
		sleep $4
	done
		echo
}
show(){
line "$1" '/' '\t' '0.001'
line "$1" "$2" '\t' '0.01'
line "$1" '/' '\t' '0.001'
echo -en '\e[?25h'
}
shengcheng(){
list=$PREFIX/share/nginx/html/list.html
archive=$PREFIX/share/nginx/html/cunc
echo '<meta http-equiv="refresh" content="1" charset="utf-8">' > $list
ls -1 $archive | sed -r 's#(.*)#<font size=123><br><a href="cunc/\1">\1</a></br></font>#' >> $list
}
dynamic(){
origin=`ls $archive | md5sum | awk '{print $1}'`
while [ 1 ]
do
	new=`ls $archive | md5sum | awk '{print $1}'`
	[ $origin != $new ] && origin=$new && shengcheng &> /dev/null
done
}
kill_scrpt(){
pid=`ps -ef |grep '.toolbox --web' | awk /bash/'{print $2}'`
for p in $pid
do
	kill $p
done
}
kill_svc(){
killall $1 &> /dev/null
#for i in `pgrep $1`
#do
#	kill $i
#done
}
cl_rbs(){
rm $PREFIX/share/nginx/html/list.html &> /dev/null
sed -i /list.html/'d' $PREFIX/var/log/nginx/access.log
}
case $1 in
	--web)
		startService;
		show "web service is running" 32;
		shengcheng;
		dynamic;;
	--gw)
		kill_scrpt;
		kill_svc nginx;
		#kill_svc mysqld;
		#kill_svc php-fpm;
		cl_rbs;
		show "web service is down" 34;;
	--github)
		push $ghp $ghl $bghl;;
	--gitee)
		push $gtp $gtl $bgtl;;
	--db)
		push $gtp $gtl $bgtl;
		push $ghp $ghl $bghl;;
	--ql)
		ql;;
	--hf)
		hf;;
	--mp3)
		mp3 $2 $3;;
	*)
		echo -e '\e[32mweb|gw|github|gitee|ql|hf|mp3\e[0m'
esac
