#!/bin/bash
ql(){
echo
ls .*.sw* 2> /dev/null
[ $? -eq 2 ] && echo -e "\t\t\e[32mNO TRASH\e[0m" && exit
echo -e "\e[32m--------------------\e[0m"
while :
read -p "sure? " s
do
	if [[ ${s:=yes} =~ yes ]];then
		rm .*.sw*
		echo -e "\t\t\e[32mTRASH CLEANED UP\e[0m"
		exit
	elif [[ $s =~ no ]];then
		exit
	else
		echo -e "\e[32myes|no\e[0m"
	fi
done
}	
hf(){
clear
echo -e '\e[0m\e[?25h'
}
push(){
bpath=$PREFIX/backup
cd
for i in `ls`;do
[ -f $i ] && rsync $i $bpath && echo -e "$i \e[32m✓\e[0m" && let e++
done
echo -e "\e[32m---------------\ncopied $e files\e[0m"
read -p "git push them all? " y
[[ "$y" =~ "no" ]] && exit
[[ "${y:=yes}" =~ "yes" ]] && rsync -r ${bpath}/ $1 && cd $1 && git add . && read -p "any remarks? " rm && git commit -m "${rm:=}`date +%Y%b%e•%X`" && git push && echo -e "$2" || echo -e "$3"
cd
}
ghl='\n\t\t\e[1m\e[37m(×)\n\t\t/|\\\e[0m\n'
gtl='\n\t\t\e[1m\e[31m(\e[37mG\e[31m)\e[0m\n'
bghl='\n\t\t\e[1m\e[33m(×)\n\t\t/|\\\e[0m\n'
bgtl='\n\t\t\e[1m\e[33m(\e[32mG\e[33m)\e[0m\n'
ghp=$HOME/termux-prc
gtp=$HOME/termux-app
startService(){
nginx
#php-fpm  
#nohup mysqld &> /dev/null &
sleep 1
clear
}
show(){
length=`echo "$1" | wc -L` 
echo -en "\033[?25l\t"
for x in `seq ${length}`;do
	echo -en "\033[$[x%7+31]m/"
	sleep 0.001
done
echo -en "\n\t"
for i in `seq ${length}`;do
	echo -en "\033[$2m${1:$[i-1]:1}\033[0m"
	sleep 0.01
done
echo -en "\n\t"
for x in `seq ${length}`;do
	echo -en "\033[$[x%7+31]m/"
	sleep 0.001
done
echo -e "\033[?25h\n\033[0m"
}
shengcheng(){
list=$PREFIX/share/nginx/html/list.html
archive=$PREFIX/share/nginx/html/cunc
ls $archive > $list
substance=`cat $list`
> $list
echo '<meta http-equiv="refresh" content="1">' > $list
for sub in $substance
do
	echo "<font size=123><br><a href=\"cunc/${sub}\">${sub}</a></br></font>" >> $list
done
}
dynamic(){
biao=$PREFIX/share/nginx/html/biao
ls $archive > $biao
origin=`md5sum $biao | awk '{print $1}'`
while [ 1 ]
do
	piao=$PREFIX/share/nginx/html/piao
	ls $archive > $piao
	new=`md5sum $piao | awk '{print $1}'`
	[ $origin != $new ] && origin=$new && shengcheng &> /dev/null
done
}
kill_scrpt(){
pid=`ps -ef |grep '.toolbox --web' | awk /bash/'{print $2}'`
for p in $pid
do
	kill $p
done
}
kill_svc(){
for i in `pgrep $1`
do
	kill $i
done
}
cl_rbs(){
rm $PREFIX/share/nginx/html/list.html &> /dev/null
rm $PREFIX/share/nginx/html/biao &> /dev/null
rm $PREFIX/share/nginx/html/piao &> /dev/null
sed -i /list.html/'d' $PREFIX/var/log/nginx/access.log
}
case $1 in
	--web)
		startService;
		show "web service is running" 32;
		shengcheng;
		dynamic;;
	--gw)
		kill_scrpt;
		kill_svc nginx;
		#kill_svc mysqld;
		#kill_svc php-fpm;
		cl_rbs;
		show "web service is down" 34;;
	--github)
		push $ghp $ghl $bghl;;
	--gitee)
		push $gtp $gtl $bgtl;;
	--db)
		push $gtp $gtl $bgtl;
		unset e;
		push $ghp $ghl $bghl;;
	--ql)
		ql;;
	--hf)
		hf;;
	*)
		echo -e '\e[32mweb|gw|github|gitee|ql|hf\e[0m'
esac
