#!/data/data/com.termux/files/usr/bin/bash
read -p "minutes:" m
read -p "seconds:" S
echo -e "\e[?25l\t\tLICLOCK\n\t\t\c"
tput sc
for s in `seq $[${m:=0}*60+${S:=0}] -1 0`
do
	c=$[s%7+31]
	tput rc
	tput ed
	f=$[s/60]
	n=$[s%60]
	[ $f -lt 10 ] && f=0$f
	[ $n -lt 10 ] && n=0$n
	echo -en "\e[${c}m${f}M ${n}S\e[0m"
	sleep 0.8559322
done
echo -e "\a\e[?25h"
